### ISSUE TITLE
Attempting to use a port that is not open

### ISSUE THREAD

**Issue by 18107** [susundberg/pebble-linux-remote#1]
I am unable to connect the pebble to my computer.
default.ini is unchanged.
OS is linux mint 17.2.

> pebble-linux-remote-master/host_python $ sudo python pebble_connection.py ./default.ini
> INFO:root:Pebble timeouted, retrying..
> Traceback (most recent call last):
>  File "pebble_connection.py", line 195, in <module>
>    main(get_settings())
>  File "pebble_connection.py", line 150, in main
>    pebble.run_async()
>  File "/home/jai/Documents/Pebble/pebble-linux-remote-master/host_python/libpebble2/communication/**init**.py", line 102, in run_async
>    self.fetch_watch_info()
>  File "/home/jai/Documents/Pebble/pebble-linux-remote-master/host_python/libpebble2/communication/**init**.py", line 278, in fetch_watch_info
>    self.send_packet(WatchVersion(data=WatchVersionRequest()))
>  File "/home/jai/Documents/Pebble/pebble-linux-remote-master/host_python/libpebble2/communication/**init**.py", line 242, in send_packet
>    self.send_raw(serialised)
>  File "/home/jai/Documents/Pebble/pebble-linux-remote-master/host_python/libpebble2/communication/**init**.py", line 254, in send_raw
>    self.transport.send_packet(message)
>  File "/home/jai/Documents/Pebble/pebble-linux-remote-master/host_python/libpebble2/communication/transports/serial.py", line 58, in send_packet
>    self.connection.write(message)
>  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 466, in write
>    if not self._isOpen: raise portNotOpenError
> ValueError: Attempting to use a port that is not open

**EDIT:** This can be solved by:
- Change NACK_COUNT_LIMIT to 50 (or at least higher than 5)
- Run the python script
- Set the pebble's bluetooth to discoverable by opening bluetooth settings
- Wait for the terminal to get spammed by "WARNING:root:NACK received for packet!
  "
- Close bluetooth settings and open the pebble app

Once this has been done once, everything appears to work as intended.

**Comment by susundberg** [comment]
Hi!

Sorry for late reply -- good to hear you got it solved.

I guess you did the pairing & binding properly ? Also, could you attach your kernel version -- just if other people hit the same problem again (on shell: uname -a). I had problems with Ubuntu 14.04 stock kernel -- i had to upgrade to 3.15 to get the app working.

I had quite low NACK limit since in "normal" behaviour you should not have any, as far as i have known so far. Afaik the NACK package means that the program (linux remote) did not receive the message (it was not running?), but the pebble os on the watch did receive the message enough to reply with nack.

**Comment by susundberg** [comment]
Closing as inactive.
